[package]
name = "pc_manager"
version = "0.0.4"
description = "PC Manager - Software de Escritorio Core-Modular para Windows (Rust + Tauri)"
authors = ["PC Manager Team"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "pc_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "pc_manager"
path = "src/main.rs"

[[bin]]
name = "pc_manager_service"
path = "src/bin/service_main.rs"

[build-dependencies]
tauri-build = { version = "2.6.3" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3", features = ["tray-icon"] }
tauri-plugin-log = "2"
zip = { version = "2.2", default-features = false, features = ["deflate"] }
tauri-plugin-notification = "2.4.0"
ed25519-dalek = { version = "2.1", default-features = false, features = ["std"] }
sha2 = "0.10"
hex = "0.4"

[target.'cfg(windows)'.dependencies]
tauri-winrt-notification = "0.7.3"
windows-sys = { version = "0.60", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Services",
    "Win32_System_Registry"
] }


